// Generated by `bun run abi` from the Forge artifacts. Do not edit.
//
// Regenerate after any change to `src/*.sol`; a stale ABI here is a decoder
// that silently returns the wrong field rather than an error anyone will see.

export const lemonVaultAbi = [
	{
		type: "constructor",
		inputs: [
			{
				name: "p",
				type: "tuple",
				internalType: "struct LemonVault.InitParams",
				components: [
					{
						name: "asset",
						type: "address",
						internalType: "contract IERC20",
					},
					{
						name: "name",
						type: "string",
						internalType: "string",
					},
					{
						name: "symbol",
						type: "string",
						internalType: "string",
					},
					{
						name: "marketId",
						type: "bytes32",
						internalType: "bytes32",
					},
					{
						name: "admin",
						type: "address",
						internalType: "address",
					},
					{
						name: "agentWallet",
						type: "address",
						internalType: "address",
					},
					{
						name: "guardian",
						type: "address",
						internalType: "address",
					},
					{
						name: "insuranceFund",
						type: "address",
						internalType: "address",
					},
					{
						name: "risk",
						type: "tuple",
						internalType: "struct LemonVault.RiskProfile",
						components: [
							{
								name: "tier",
								type: "uint8",
								internalType: "enum LemonVault.RiskTier",
							},
							{
								name: "targetLeverageBps",
								type: "uint32",
								internalType: "uint32",
							},
							{
								name: "maxLeverageBps",
								type: "uint32",
								internalType: "uint32",
							},
						],
					},
					{
						name: "limits",
						type: "tuple",
						internalType: "struct LemonVault.Limits",
						components: [
							{
								name: "managementFeeBps",
								type: "uint16",
								internalType: "uint16",
							},
							{
								name: "performanceFeeBps",
								type: "uint16",
								internalType: "uint16",
							},
							{
								name: "minRedeemDelay",
								type: "uint32",
								internalType: "uint32",
							},
							{
								name: "maxRedeemDelay",
								type: "uint32",
								internalType: "uint32",
							},
							{
								name: "maxDeployedBps",
								type: "uint16",
								internalType: "uint16",
							},
							{
								name: "maxNavDeviationBps",
								type: "uint16",
								internalType: "uint16",
							},
							{
								name: "maxNavEpochDeviationBps",
								type: "uint16",
								internalType: "uint16",
							},
							{
								name: "navEpochDuration",
								type: "uint32",
								internalType: "uint32",
							},
							{
								name: "minNavReportInterval",
								type: "uint32",
								internalType: "uint32",
							},
							{
								name: "maxNavStaleness",
								type: "uint32",
								internalType: "uint32",
							},
							{
								name: "agentWithdrawWindowCap",
								type: "uint256",
								internalType: "uint256",
							},
							{
								name: "agentWithdrawWindow",
								type: "uint32",
								internalType: "uint32",
							},
						],
					},
				],
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "AGENT_ROLE",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "DEFAULT_ADMIN_ROLE",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "GUARDIAN_ROLE",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "MAX_LEVERAGE_BPS",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "MAX_MANAGEMENT_FEE_BPS",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint16",
				internalType: "uint16",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "MAX_PERFORMANCE_FEE_BPS",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint16",
				internalType: "uint16",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "MAX_REDEEM_DELAY",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "NO_LEVERAGE_BPS",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "REQUEST_ID",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "accrueFees",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "activityCount",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "agentReturn",
		inputs: [
			{
				name: "amount",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "agentWallet",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "agentWithdraw",
		inputs: [
			{
				name: "amount",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "allowance",
		inputs: [
			{
				name: "owner",
				type: "address",
				internalType: "address",
			},
			{
				name: "spender",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "approve",
		inputs: [
			{
				name: "spender",
				type: "address",
				internalType: "address",
			},
			{
				name: "value",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "asset",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "balanceOf",
		inputs: [
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "claimableAssets",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "claimableRedeemRequest",
		inputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "convertToAssets",
		inputs: [
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "convertToShares",
		inputs: [
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "cumulativeNotional",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "cumulativeVenueFees",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "decimals",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint8",
				internalType: "uint8",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "deployedAssets",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "deposit",
		inputs: [
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "emergencyExit",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "freeAssets",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "fulfillRedeem",
		inputs: [
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "getRoleAdmin",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "grantRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "hasRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "highWaterMarkPps",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "insuranceFund",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "isOperator",
		inputs: [
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
			{
				name: "operator",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "lastFeeAccrualAt",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint64",
				internalType: "uint64",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "lastNavReportAt",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint64",
				internalType: "uint64",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "lastObservedLeverageBps",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "limits",
		inputs: [],
		outputs: [
			{
				name: "managementFeeBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "performanceFeeBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "minRedeemDelay",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "maxRedeemDelay",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "maxDeployedBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "maxNavDeviationBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "maxNavEpochDeviationBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "navEpochDuration",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "minNavReportInterval",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "maxNavStaleness",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "agentWithdrawWindowCap",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "agentWithdrawWindow",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "marketId",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "maxDeposit",
		inputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "maxLeverageBps",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "maxMint",
		inputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "maxRedeem",
		inputs: [
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "maxWithdraw",
		inputs: [
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "mint",
		inputs: [
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "name",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "string",
				internalType: "string",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "navEpochAnchor",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "navEpochStartedAt",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint64",
				internalType: "uint64",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "navIsStale",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "pause",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "paused",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "pendingRedeemRequest",
		inputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "previewDeposit",
		inputs: [
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "previewMint",
		inputs: [
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "previewRedeem",
		inputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "pure",
	},
	{
		type: "function",
		name: "previewWithdraw",
		inputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "pure",
	},
	{
		type: "function",
		name: "pricePerShare",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "redeem",
		inputs: [
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "redeemStateOf",
		inputs: [
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "pendingShares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "pendingClaimableShares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "pendingClaimableAssets",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "requestedAt",
				type: "uint64",
				internalType: "uint64",
			},
			{
				name: "eligibleAt",
				type: "uint64",
				internalType: "uint64",
			},
			{
				name: "fulfillBy",
				type: "uint64",
				internalType: "uint64",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "renounceRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "callerConfirmation",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "reportActivity",
		inputs: [
			{
				name: "report",
				type: "tuple",
				internalType: "struct LemonVault.ActivityReport",
				components: [
					{
						name: "kind",
						type: "uint8",
						internalType: "enum LemonVault.ActivityKind",
					},
					{
						name: "chain",
						type: "uint8",
						internalType: "enum LemonVault.Chain",
					},
					{
						name: "symbol",
						type: "bytes32",
						internalType: "bytes32",
					},
					{
						name: "baseAmount",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "notionalAssets",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "pnlAssets",
						type: "int256",
						internalType: "int256",
					},
					{
						name: "feeAssets",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "txRef",
						type: "bytes",
						internalType: "bytes",
					},
					{
						name: "occurredAt",
						type: "uint64",
						internalType: "uint64",
					},
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "reportActivityBatch",
		inputs: [
			{
				name: "reports",
				type: "tuple[]",
				internalType: "struct LemonVault.ActivityReport[]",
				components: [
					{
						name: "kind",
						type: "uint8",
						internalType: "enum LemonVault.ActivityKind",
					},
					{
						name: "chain",
						type: "uint8",
						internalType: "enum LemonVault.Chain",
					},
					{
						name: "symbol",
						type: "bytes32",
						internalType: "bytes32",
					},
					{
						name: "baseAmount",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "notionalAssets",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "pnlAssets",
						type: "int256",
						internalType: "int256",
					},
					{
						name: "feeAssets",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "txRef",
						type: "bytes",
						internalType: "bytes",
					},
					{
						name: "occurredAt",
						type: "uint64",
						internalType: "uint64",
					},
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "reportNav",
		inputs: [
			{
				name: "newDeployedAssets",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "observedLeverageBps",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "observedAt",
				type: "uint64",
				internalType: "uint64",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "requestRedeem",
		inputs: [
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
			{
				name: "owner",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "revokeRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "riskTier",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint8",
				internalType: "enum LemonVault.RiskTier",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "setEmergencyExit",
		inputs: [
			{
				name: "enabled",
				type: "bool",
				internalType: "bool",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setInsuranceFund",
		inputs: [
			{
				name: "next",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setLimits",
		inputs: [
			{
				name: "next",
				type: "tuple",
				internalType: "struct LemonVault.Limits",
				components: [
					{
						name: "managementFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "performanceFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "minRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxDeployedBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavEpochDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "navEpochDuration",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "minNavReportInterval",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxNavStaleness",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "agentWithdrawWindowCap",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "agentWithdrawWindow",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setOperator",
		inputs: [
			{
				name: "operator",
				type: "address",
				internalType: "address",
			},
			{
				name: "approved",
				type: "bool",
				internalType: "bool",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "supportsInterface",
		inputs: [
			{
				name: "interfaceId",
				type: "bytes4",
				internalType: "bytes4",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "symbol",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "string",
				internalType: "string",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "targetLeverageBps",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "totalAssets",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "totalPendingRedeemShares",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "totalSupply",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "transfer",
		inputs: [
			{
				name: "to",
				type: "address",
				internalType: "address",
			},
			{
				name: "value",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "transferFrom",
		inputs: [
			{
				name: "from",
				type: "address",
				internalType: "address",
			},
			{
				name: "to",
				type: "address",
				internalType: "address",
			},
			{
				name: "value",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "unpause",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "withdraw",
		inputs: [
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
			{
				name: "controller",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "event",
		name: "ActivityReported",
		inputs: [
			{
				name: "sequence",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "kind",
				type: "uint8",
				indexed: true,
				internalType: "enum LemonVault.ActivityKind",
			},
			{
				name: "chain",
				type: "uint8",
				indexed: false,
				internalType: "enum LemonVault.Chain",
			},
			{
				name: "symbol",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "baseAmount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "notionalAssets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "pnlAssets",
				type: "int256",
				indexed: false,
				internalType: "int256",
			},
			{
				name: "feeAssets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "txRef",
				type: "bytes",
				indexed: false,
				internalType: "bytes",
			},
			{
				name: "occurredAt",
				type: "uint64",
				indexed: false,
				internalType: "uint64",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "AgentReturned",
		inputs: [
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "deployedAssets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "AgentWithdrew",
		inputs: [
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "deployedAssets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Approval",
		inputs: [
			{
				name: "owner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "spender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "value",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Deposit",
		inputs: [
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "owner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "assets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "EmergencyExitSet",
		inputs: [
			{
				name: "enabled",
				type: "bool",
				indexed: false,
				internalType: "bool",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "FeesAccrued",
		inputs: [
			{
				name: "managementShares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "performanceShares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "newHighWaterMark",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "InsuranceFundUpdated",
		inputs: [
			{
				name: "insuranceFund",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "LimitsUpdated",
		inputs: [
			{
				name: "limits",
				type: "tuple",
				indexed: false,
				internalType: "struct LemonVault.Limits",
				components: [
					{
						name: "managementFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "performanceFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "minRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxDeployedBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavEpochDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "navEpochDuration",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "minNavReportInterval",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxNavStaleness",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "agentWithdrawWindowCap",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "agentWithdrawWindow",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "NavReported",
		inputs: [
			{
				name: "deployedAssets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "totalAssets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "pricePerShare",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "leverageBps",
				type: "uint32",
				indexed: false,
				internalType: "uint32",
			},
			{
				name: "observedAt",
				type: "uint64",
				indexed: false,
				internalType: "uint64",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "OperatorSet",
		inputs: [
			{
				name: "controller",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "operator",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "approved",
				type: "bool",
				indexed: false,
				internalType: "bool",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Paused",
		inputs: [
			{
				name: "account",
				type: "address",
				indexed: false,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RedeemClaimed",
		inputs: [
			{
				name: "controller",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "receiver",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "assets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RedeemFulfilled",
		inputs: [
			{
				name: "controller",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "assets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RedeemQueued",
		inputs: [
			{
				name: "controller",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "eligibleAt",
				type: "uint64",
				indexed: false,
				internalType: "uint64",
			},
			{
				name: "fulfillBy",
				type: "uint64",
				indexed: false,
				internalType: "uint64",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RedeemRequest",
		inputs: [
			{
				name: "controller",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "owner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "requestId",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "sender",
				type: "address",
				indexed: false,
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleAdminChanged",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "previousAdminRole",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "newAdminRole",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleGranted",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleRevoked",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Transfer",
		inputs: [
			{
				name: "from",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "to",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "value",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Unpaused",
		inputs: [
			{
				name: "account",
				type: "address",
				indexed: false,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Withdraw",
		inputs: [
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "receiver",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "owner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "assets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "error",
		name: "AccessControlBadConfirmation",
		inputs: [],
	},
	{
		type: "error",
		name: "AccessControlUnauthorizedAccount",
		inputs: [
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
			{
				name: "neededRole",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
	},
	{
		type: "error",
		name: "AgentWindowCapExceeded",
		inputs: [
			{
				name: "requested",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "remaining",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "AgentWithdrawalsDisabled",
		inputs: [],
	},
	{
		type: "error",
		name: "AsyncRedemptionOnly",
		inputs: [],
	},
	{
		type: "error",
		name: "CannotReportNavWithNothingDeployed",
		inputs: [],
	},
	{
		type: "error",
		name: "DeployedCeilingExceeded",
		inputs: [
			{
				name: "proposed",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "ceiling",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ERC20InsufficientAllowance",
		inputs: [
			{
				name: "spender",
				type: "address",
				internalType: "address",
			},
			{
				name: "allowance",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "needed",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ERC20InsufficientBalance",
		inputs: [
			{
				name: "sender",
				type: "address",
				internalType: "address",
			},
			{
				name: "balance",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "needed",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ERC20InvalidApprover",
		inputs: [
			{
				name: "approver",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "ERC20InvalidReceiver",
		inputs: [
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "ERC20InvalidSender",
		inputs: [
			{
				name: "sender",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "ERC20InvalidSpender",
		inputs: [
			{
				name: "spender",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "ERC4626ExceededMaxDeposit",
		inputs: [
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "max",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ERC4626ExceededMaxMint",
		inputs: [
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "max",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ERC4626ExceededMaxRedeem",
		inputs: [
			{
				name: "owner",
				type: "address",
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "max",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ERC4626ExceededMaxWithdraw",
		inputs: [
			{
				name: "owner",
				type: "address",
				internalType: "address",
			},
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "max",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "EnforcedPause",
		inputs: [],
	},
	{
		type: "error",
		name: "ExceedsClaimableRequest",
		inputs: [
			{
				name: "requested",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "claimable",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ExceedsPendingRequest",
		inputs: [
			{
				name: "requested",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "pending",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "ExpectedPause",
		inputs: [],
	},
	{
		type: "error",
		name: "InsufficientFreeAssets",
		inputs: [
			{
				name: "requested",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "available",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "InvalidLimits",
		inputs: [],
	},
	{
		type: "error",
		name: "InvalidRiskProfile",
		inputs: [],
	},
	{
		type: "error",
		name: "LeverageExceedsMandate",
		inputs: [
			{
				name: "observed",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "ceiling",
				type: "uint32",
				internalType: "uint32",
			},
		],
	},
	{
		type: "error",
		name: "NavDeviationTooLarge",
		inputs: [
			{
				name: "proposed",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "bound",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "NavEpochDeviationTooLarge",
		inputs: [
			{
				name: "proposed",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "bound",
				type: "uint256",
				internalType: "uint256",
			},
		],
	},
	{
		type: "error",
		name: "NavReportTooSoon",
		inputs: [],
	},
	{
		type: "error",
		name: "NavStale",
		inputs: [],
	},
	{
		type: "error",
		name: "NotAuthorized",
		inputs: [],
	},
	{
		type: "error",
		name: "RedeemDelayNotElapsed",
		inputs: [
			{
				name: "eligibleAt",
				type: "uint64",
				internalType: "uint64",
			},
		],
	},
	{
		type: "error",
		name: "SafeERC20FailedOperation",
		inputs: [
			{
				name: "token",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "ZeroAddress",
		inputs: [],
	},
	{
		type: "error",
		name: "ZeroAmount",
		inputs: [],
	},
] as const;

export const vaultFactoryAbi = [
	{
		type: "constructor",
		inputs: [
			{
				name: "asset_",
				type: "address",
				internalType: "contract IERC20",
			},
			{
				name: "admin",
				type: "address",
				internalType: "address",
			},
			{
				name: "vaultAdmin_",
				type: "address",
				internalType: "address",
			},
			{
				name: "guardian_",
				type: "address",
				internalType: "address",
			},
			{
				name: "insuranceFund_",
				type: "address",
				internalType: "address",
			},
			{
				name: "conservativeLimits",
				type: "tuple",
				internalType: "struct LemonVault.Limits",
				components: [
					{
						name: "managementFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "performanceFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "minRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxDeployedBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavEpochDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "navEpochDuration",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "minNavReportInterval",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxNavStaleness",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "agentWithdrawWindowCap",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "agentWithdrawWindow",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
			{
				name: "leveragedLimits",
				type: "tuple",
				internalType: "struct LemonVault.Limits",
				components: [
					{
						name: "managementFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "performanceFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "minRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxDeployedBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavEpochDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "navEpochDuration",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "minNavReportInterval",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxNavStaleness",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "agentWithdrawWindowCap",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "agentWithdrawWindow",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "DEFAULT_ADMIN_ROLE",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "VAULT_ADMIN_ROLE",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "asset",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address",
				internalType: "contract IERC20",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "createVault",
		inputs: [
			{
				name: "marketId",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "agentWallet",
				type: "address",
				internalType: "address",
			},
			{
				name: "name",
				type: "string",
				internalType: "string",
			},
			{
				name: "symbol",
				type: "string",
				internalType: "string",
			},
			{
				name: "risk",
				type: "tuple",
				internalType: "struct LemonVault.RiskProfile",
				components: [
					{
						name: "tier",
						type: "uint8",
						internalType: "enum LemonVault.RiskTier",
					},
					{
						name: "targetLeverageBps",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxLeverageBps",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
		],
		outputs: [
			{
				name: "vault",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "createVaultWithLimits",
		inputs: [
			{
				name: "marketId",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "agentWallet",
				type: "address",
				internalType: "address",
			},
			{
				name: "name",
				type: "string",
				internalType: "string",
			},
			{
				name: "symbol",
				type: "string",
				internalType: "string",
			},
			{
				name: "risk",
				type: "tuple",
				internalType: "struct LemonVault.RiskProfile",
				components: [
					{
						name: "tier",
						type: "uint8",
						internalType: "enum LemonVault.RiskTier",
					},
					{
						name: "targetLeverageBps",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxLeverageBps",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
			{
				name: "limits",
				type: "tuple",
				internalType: "struct LemonVault.Limits",
				components: [
					{
						name: "managementFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "performanceFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "minRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxDeployedBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavEpochDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "navEpochDuration",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "minNavReportInterval",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxNavStaleness",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "agentWithdrawWindowCap",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "agentWithdrawWindow",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
		],
		outputs: [
			{
				name: "vault",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "defaultLimits",
		inputs: [
			{
				name: "tier",
				type: "uint8",
				internalType: "enum LemonVault.RiskTier",
			},
		],
		outputs: [
			{
				name: "managementFeeBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "performanceFeeBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "minRedeemDelay",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "maxRedeemDelay",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "maxDeployedBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "maxNavDeviationBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "maxNavEpochDeviationBps",
				type: "uint16",
				internalType: "uint16",
			},
			{
				name: "navEpochDuration",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "minNavReportInterval",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "maxNavStaleness",
				type: "uint32",
				internalType: "uint32",
			},
			{
				name: "agentWithdrawWindowCap",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "agentWithdrawWindow",
				type: "uint32",
				internalType: "uint32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getRoleAdmin",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "grantRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "guardian",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "hasRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "insuranceFund",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "renounceRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "callerConfirmation",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "revokeRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setDefaultLimits",
		inputs: [
			{
				name: "tier",
				type: "uint8",
				internalType: "enum LemonVault.RiskTier",
			},
			{
				name: "limits",
				type: "tuple",
				internalType: "struct LemonVault.Limits",
				components: [
					{
						name: "managementFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "performanceFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "minRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxDeployedBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavEpochDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "navEpochDuration",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "minNavReportInterval",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxNavStaleness",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "agentWithdrawWindowCap",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "agentWithdrawWindow",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setDefaults",
		inputs: [
			{
				name: "vaultAdmin_",
				type: "address",
				internalType: "address",
			},
			{
				name: "guardian_",
				type: "address",
				internalType: "address",
			},
			{
				name: "insuranceFund_",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "supportsInterface",
		inputs: [
			{
				name: "interfaceId",
				type: "bytes4",
				internalType: "bytes4",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "vaultAdmin",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "vaultCount",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "vaultForAgent",
		inputs: [
			{
				name: "agent",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "vault",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "vaultForMarket",
		inputs: [
			{
				name: "marketId",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		outputs: [
			{
				name: "vault",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "vaults",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "address[]",
				internalType: "address[]",
			},
		],
		stateMutability: "view",
	},
	{
		type: "event",
		name: "DefaultLimitsUpdated",
		inputs: [
			{
				name: "tier",
				type: "uint8",
				indexed: true,
				internalType: "enum LemonVault.RiskTier",
			},
			{
				name: "limits",
				type: "tuple",
				indexed: false,
				internalType: "struct LemonVault.Limits",
				components: [
					{
						name: "managementFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "performanceFeeBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "minRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxRedeemDelay",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxDeployedBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "maxNavEpochDeviationBps",
						type: "uint16",
						internalType: "uint16",
					},
					{
						name: "navEpochDuration",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "minNavReportInterval",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "maxNavStaleness",
						type: "uint32",
						internalType: "uint32",
					},
					{
						name: "agentWithdrawWindowCap",
						type: "uint256",
						internalType: "uint256",
					},
					{
						name: "agentWithdrawWindow",
						type: "uint32",
						internalType: "uint32",
					},
				],
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "DefaultsUpdated",
		inputs: [
			{
				name: "vaultAdmin",
				type: "address",
				indexed: false,
				internalType: "address",
			},
			{
				name: "guardian",
				type: "address",
				indexed: false,
				internalType: "address",
			},
			{
				name: "insuranceFund",
				type: "address",
				indexed: false,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleAdminChanged",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "previousAdminRole",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "newAdminRole",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleGranted",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleRevoked",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "VaultCreated",
		inputs: [
			{
				name: "vault",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "marketId",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "agentWallet",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "name",
				type: "string",
				indexed: false,
				internalType: "string",
			},
			{
				name: "symbol",
				type: "string",
				indexed: false,
				internalType: "string",
			},
			{
				name: "tier",
				type: "uint8",
				indexed: false,
				internalType: "enum LemonVault.RiskTier",
			},
			{
				name: "targetLeverageBps",
				type: "uint32",
				indexed: false,
				internalType: "uint32",
			},
			{
				name: "maxLeverageBps",
				type: "uint32",
				indexed: false,
				internalType: "uint32",
			},
		],
		anonymous: false,
	},
	{
		type: "error",
		name: "AccessControlBadConfirmation",
		inputs: [],
	},
	{
		type: "error",
		name: "AccessControlUnauthorizedAccount",
		inputs: [
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
			{
				name: "neededRole",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
	},
	{
		type: "error",
		name: "AgentAlreadyAssigned",
		inputs: [
			{
				name: "agent",
				type: "address",
				internalType: "address",
			},
			{
				name: "vault",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "MarketAlreadyVaulted",
		inputs: [
			{
				name: "marketId",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "vault",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "ZeroAddress",
		inputs: [],
	},
] as const;

export const insuranceFundAbi = [
	{
		type: "constructor",
		inputs: [
			{
				name: "admin",
				type: "address",
				internalType: "address",
			},
			{
				name: "treasurer",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "DEFAULT_ADMIN_ROLE",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "TREASURER_ROLE",
		inputs: [],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "claimExit",
		inputs: [
			{
				name: "vault",
				type: "address",
				internalType: "contract LemonVault",
			},
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
			{
				name: "receiver",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "assets",
				type: "uint256",
				internalType: "uint256",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "cover",
		inputs: [
			{
				name: "vault",
				type: "address",
				internalType: "contract LemonVault",
			},
			{
				name: "amount",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "getRoleAdmin",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		outputs: [
			{
				name: "",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "grantRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "hasRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "renounceRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "callerConfirmation",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "requestExit",
		inputs: [
			{
				name: "vault",
				type: "address",
				internalType: "contract LemonVault",
			},
			{
				name: "shares",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "revokeRole",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "supportsInterface",
		inputs: [
			{
				name: "interfaceId",
				type: "bytes4",
				internalType: "bytes4",
			},
		],
		outputs: [
			{
				name: "",
				type: "bool",
				internalType: "bool",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "sweep",
		inputs: [
			{
				name: "token",
				type: "address",
				internalType: "contract IERC20",
			},
			{
				name: "to",
				type: "address",
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				internalType: "uint256",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "event",
		name: "Covered",
		inputs: [
			{
				name: "vault",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ExitClaimed",
		inputs: [
			{
				name: "vault",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "assets",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ExitRequested",
		inputs: [
			{
				name: "vault",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "shares",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleAdminChanged",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "previousAdminRole",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "newAdminRole",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleGranted",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RoleRevoked",
		inputs: [
			{
				name: "role",
				type: "bytes32",
				indexed: true,
				internalType: "bytes32",
			},
			{
				name: "account",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "sender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Swept",
		inputs: [
			{
				name: "token",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "to",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "error",
		name: "AccessControlBadConfirmation",
		inputs: [],
	},
	{
		type: "error",
		name: "AccessControlUnauthorizedAccount",
		inputs: [
			{
				name: "account",
				type: "address",
				internalType: "address",
			},
			{
				name: "neededRole",
				type: "bytes32",
				internalType: "bytes32",
			},
		],
	},
	{
		type: "error",
		name: "SafeERC20FailedOperation",
		inputs: [
			{
				name: "token",
				type: "address",
				internalType: "address",
			},
		],
	},
	{
		type: "error",
		name: "ZeroAddress",
		inputs: [],
	},
	{
		type: "error",
		name: "ZeroAmount",
		inputs: [],
	},
] as const;
