/**
 * Extract the ABIs Forge produced into a typed TypeScript module.
 *
 * The API, the indexer, the agent and the web app all need these, and copying a
 * JSON artifact into four packages is how three of them end up a deploy behind.
 * Generating one `const` with `as const` instead gives viem full type inference
 * on every call and event, so a renamed argument is a type error at build time
 * rather than an undefined at runtime.
 *
 * Run `bun run abi` after any `forge build`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

/** Contracts whose ABI is part of this package's public surface. */
const CONTRACTS = ["LemonVault", "VaultFactory", "InsuranceFund"] as const;

interface Artifact {
	abi: unknown[];
}

function readAbi(name: string): unknown[] {
	const path = join(root, "out", `${name}.sol`, `${name}.json`);
	try {
		const artifact = JSON.parse(readFileSync(path, "utf8")) as Artifact;
		return artifact.abi;
	} catch (error) {
		throw new Error(
			`No artifact for ${name} at ${path}. Run \`forge build\` first. (${String(error)})`,
		);
	}
}

const banner = `// Generated by \`bun run abi\` from the Forge artifacts. Do not edit.
//
// Regenerate after any change to \`src/*.sol\`; a stale ABI here is a decoder
// that silently returns the wrong field rather than an error anyone will see.
`;

const parts: string[] = [banner];

for (const name of CONTRACTS) {
	const abi = readAbi(name);
	const constName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
	parts.push(`export const ${constName} = ${JSON.stringify(abi, null, "\t")} as const;\n`);
}

const outDir = join(root, "ts");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "abi.ts"), parts.join("\n"));

console.log(`[contracts] wrote ts/abi.ts (${CONTRACTS.join(", ")})`);
