import { describe, expect, test } from "bun:test";
import {
	appendAttributionSuffix,
	encodeAttributionSuffix,
	isValidBps,
	MAX_SPOT_FEE_BPS,
	NO_FEES,
} from "../src/fees";

describe("spot fee validation", () => {
	test("accepts the range KyberSwap allows", () => {
		expect(isValidBps(0)).toBe(true);
		expect(isValidBps(30)).toBe(true);
		expect(isValidBps(MAX_SPOT_FEE_BPS)).toBe(true);
	});

	test("rejects values KyberSwap would reject", () => {
		// Sending an out-of-range fee makes every quote fail, so it is caught
		// at config time rather than at trade time.
		expect(isValidBps(MAX_SPOT_FEE_BPS + 1)).toBe(false);
		expect(isValidBps(-1)).toBe(false);
		expect(isValidBps(Number.NaN)).toBe(false);
		expect(isValidBps(Number.POSITIVE_INFINITY)).toBe(false);
	});

	test("no fees is the default", () => {
		expect(NO_FEES.spot).toBeNull();
		expect(NO_FEES.builder).toBeNull();
	});
});

describe("attribution suffix", () => {
	test("appends the suffix without its 0x prefix", () => {
		expect(appendAttributionSuffix("0xdeadbeef", "0xcafe")).toBe("0xdeadbeefcafe");
	});

	test("leaves calldata untouched when there is no code", () => {
		// The gasless path passes null here; the calldata must round-trip exactly.
		expect(appendAttributionSuffix("0xdeadbeef", null)).toBe("0xdeadbeef");
		expect(appendAttributionSuffix("0xdeadbeef", "0x")).toBe("0xdeadbeef");
	});

	test("preserves the original calldata as a prefix", () => {
		const data = "0x1234abcd";
		const result = appendAttributionSuffix(data, "0xbeef");
		expect(result.startsWith(data)).toBe(true);
	});
});

describe("ERC-8021 encoding", () => {
	/**
	 * Vectors generated by the reference implementation (ox@1.7.4
	 * `Attribution.toDataSuffix`). They are what makes hand-rolling the encoder
	 * safe: a silent format mistake means fees never attribute on-chain, which
	 * would be invisible without these.
	 */
	const VECTORS: [string[], string][] = [
		[["baseapp", "morpho"], "0x626173656170702c6d6f7270686f0e0080218021802180218021802180218021"],
		[["lemon"], "0x6c656d6f6e050080218021802180218021802180218021"],
		[["a"], "0x61010080218021802180218021802180218021"],
		[["lemon-markets"], "0x6c656d6f6e2d6d61726b6574730d0080218021802180218021802180218021"],
		[
			["x".repeat(31)],
			"0x787878787878787878787878787878787878787878787878787878787878781f0080218021802180218021802180218021",
		],
	];

	for (const [codes, expected] of VECTORS) {
		test(`matches the reference for ${JSON.stringify(codes)}`, () => {
			expect(encodeAttributionSuffix(codes)).toBe(expected);
		});
	}

	test("always ends with the ERC-8021 marker", () => {
		expect(encodeAttributionSuffix(["lemon"]).endsWith("80218021802180218021802180218021")).toBe(
			true,
		);
	});

	test("rejects codes too long for the one-byte length field", () => {
		expect(() => encodeAttributionSuffix(["x".repeat(256)])).toThrow(/255/);
	});
});
