import type { Address, Hex } from "./types";

/**
 * Integrator fee configuration.
 *
 * The two venues collect fees by completely different mechanisms, so they are
 * modelled separately rather than as one "fee percent" that would silently
 * apply to only half the app:
 *
 * - **Spot** — KyberSwap takes the fee inside the swap itself. It is a first
 *   class parameter of the route request, so it always applies.
 * - **Perp** — the reference design uses ERC-8021 builder codes: a registry entry holding
 *   the fee config, referenced by an attribution suffix appended to the
 *   transaction calldata. The rate lives on-chain in the registry, not here.
 */
export interface SpotFeeConfig {
	/** Fee in basis points (100 = 1%). KyberSwap caps this. */
	bps: number;
	/** Address that receives the fee. */
	receiver: Address;
	/**
	 * Which side of the swap the fee is taken from.
	 *
	 * `currency_in` charges before the swap and is the predictable choice —
	 * `currency_out` varies with the fill.
	 */
	chargeBy: "currency_in" | "currency_out";
}

export interface BuilderCodeConfig {
	/** Registered builder code (1-31 chars, or a 32-byte 0x-hex value). */
	code: string;
}

export interface FeeConfig {
	spot: SpotFeeConfig | null;
	builder: BuilderCodeConfig | null;
}

export const NO_FEES: FeeConfig = { spot: null, builder: null };

/** KyberSwap rejects fees above this. */
export const MAX_SPOT_FEE_BPS = 2000;

export function isValidBps(bps: number): boolean {
	return Number.isFinite(bps) && bps >= 0 && bps <= MAX_SPOT_FEE_BPS;
}

/** ERC-8021 trailer that marks the end of an attribution suffix. */
const ERC8021_MARKER = "80218021802180218021802180218021";

/** Schema 0 = canonical code registry, which is what the reference design builder codes use. */
const SCHEMA_CANONICAL_REGISTRY = 0;

/**
 * Build an ERC-8021 schema-0 attribution suffix.
 *
 * Layout: `utf8(codes joined by ",") ∥ codesLength (1 byte) ∥ schemaId (1 byte)
 * ∥ marker (16 bytes)`.
 *
 * Implemented here rather than pulling in `ox`, whose `erc8021` module only
 * exists in v1.x: viem pins ox to 0.11.3, and forcing two majors of it into one
 * app to gain twelve lines of encoding is a bad trade. The format is verified
 * against vectors generated by the real library in `fees.test.ts`.
 */
export function encodeAttributionSuffix(codes: readonly string[]): Hex {
	const joined = codes.join(",");
	const bytes = new TextEncoder().encode(joined);

	// The length field is one byte, so the encoding simply cannot describe more.
	if (bytes.length > 255) {
		throw new Error(`Attribution codes are ${bytes.length} bytes; the limit is 255.`);
	}

	const codesHex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
	const lengthHex = bytes.length.toString(16).padStart(2, "0");
	const schemaHex = SCHEMA_CANONICAL_REGISTRY.toString(16).padStart(2, "0");

	return `0x${codesHex}${lengthHex}${schemaHex}${ERC8021_MARKER}` as Hex;
}

/**
 * Append an ERC-8021 attribution suffix to transaction calldata.
 *
 * Only usable on transactions this app builds and sends itself. A gasless
 * The reference design intent is submitted by the operator, which constructs its own
 * calldata — so a suffix added client-side would never reach the chain, and
 * builder fees do not accrue on that path. The `attributed` flag on the API
 * response tells callers when that is the case rather than leaving them to
 * assume a fee was taken.
 */
export function appendAttributionSuffix(data: Hex, suffix: Hex | null): Hex {
	if (!suffix || suffix === "0x") return data;
	return `${data}${suffix.slice(2)}` as Hex;
}

/**
 * Venue taker fees, as a percent of notional per fill.
 *
 * Both legs of a basis position cross the spread as takers, and both are
 * charged the same rate, so a round trip costs four fills:
 * `2 legs x 2 (entry + exit) x 0.1% = 0.4%` of notional before any slippage.
 *
 * That figure is the whole reason a basis position has a minimum holding
 * period. At 8% annualised funding, 0.4% takes roughly eighteen days to earn
 * back — so a plan that omits it advertises a yield the position cannot
 * actually deliver. Kept here as one constant rather than duplicated across the
 * planner and the board, because the two disagreeing would mean the ranked APY
 * and the quoted APY are computed from different costs.
 */
export const VENUE_FEES = {
	/** KyberSwap route, taken inside the swap. */
	spotTakerPercent: 0.1,
	/** Pacifica market order. */
	perpTakerPercent: 0.1,
} as const;

/** Every fee paid opening and closing both legs, as a percent of notional. */
export const ROUND_TRIP_FEE_PERCENT =
	2 * (VENUE_FEES.spotTakerPercent + VENUE_FEES.perpTakerPercent);
