#!/usr/bin/env bash
#
# Deploy the protocol to a public testnet and write the overlay the app reads.
#
# Two targets, because they answer different questions.
#
#   sepolia   Base Sepolia. A persistent, wallet-connectable chain with Circle's
#             own test USDC on it, so a link can be shared and somebody can
#             deposit from their own wallet. This is the one to demo.
#
#   vibenet   Base Vibenet, chain 84538453. Base's ephemeral preview net for
#             in-flight chain features. Nothing else is deployed there — no
#             USDC, no aggregator — so this deploys its own test token, and the
#             only question it answers is whether the contracts build and behave
#             under Base's next-gen stack before it reaches Sepolia. It resets;
#             do not point anything lasting at it.
#
# Neither can run the spot leg. KyberSwap's aggregator serves Base mainnet only,
# so the agent's swap has no route on either chain — use the mainnet fork
# (scripts/fork-up.sh) for anything that has to actually fill. The perp leg is
# separate and does work: it is Pacifica's own testnet on Solana, wired below.
#
# Usage: scripts/testnet-up.sh <sepolia|vibenet>

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TARGET="${1:-}"
case "$TARGET" in
	sepolia)
		RPC="${BASE_SEPOLIA_RPC_URL:-https://sepolia.base.org}"
		CHAIN_ID=84532
		# Circle's test USDC on Base Sepolia. Faucet: faucet.circle.com.
		ASSET=0x036CbD53842c5426634e7929541eC2318f3dCF7e
		EXPLORER=https://sepolia.basescan.org
		ENV_FILE=.env.sepolia
		GAS_MULTIPLIER=130
		;;
	vibenet)
		RPC="${BASE_VIBENET_RPC_URL:-https://rpc.vibes.base.org}"
		CHAIN_ID=84538453
		# No stablecoin exists here; DeployTestnet deploys a FaucetUSDC instead.
		ASSET=""
		EXPLORER=https://explorer.vibes.base.org
		ENV_FILE=.env.vibenet
		# Vibenet's block gas limit is 6,000,000 — two orders of magnitude below
		# Base Sepolia's. `VaultFactory`'s constructor costs 5,128,976, which
		# fits, but forge's default 1.3x estimation buffer asks for 6.67M and the
		# node rejects the transaction outright with `intrinsic gas too high`.
		# 1.05x asks for 5.39M and lands. If the factory ever grows past ~5.7M
		# this target stops working entirely, which is worth knowing: Vibenet is
		# the tightest chain this protocol is expected to fit on.
		GAS_MULTIPLIER=105
		;;
	*)
		echo "usage: scripts/testnet-up.sh <sepolia|vibenet>" >&2
		exit 1
		;;
esac

if [[ -z "${DEPLOYER_PRIVATE_KEY:-}" ]]; then
	# shellcheck disable=SC1091
	[[ -f .env.deployer ]] && source .env.deployer
fi
if [[ -z "${DEPLOYER_PRIVATE_KEY:-}" ]]; then
	echo "DEPLOYER_PRIVATE_KEY is not set. Put it in .env.deployer (gitignored)." >&2
	exit 1
fi

DEPLOYER="$(cast wallet address --private-key "$DEPLOYER_PRIVATE_KEY")"

ACTUAL_CHAIN="$(cast chain-id --rpc-url "$RPC")"
if [[ "$ACTUAL_CHAIN" != "$CHAIN_ID" ]]; then
	echo "expected chain ${CHAIN_ID} at ${RPC}, got ${ACTUAL_CHAIN}" >&2
	exit 1
fi

BALANCE="$(cast balance "$DEPLOYER" --rpc-url "$RPC")"
echo "==> ${TARGET} (chain ${CHAIN_ID})"
echo "    deployer ${DEPLOYER}"
echo "    balance  $(cast to-unit "$BALANCE" ether) ETH"
if [[ "$BALANCE" == "0" ]]; then
	echo
	echo "The deployer has no gas. Fund ${DEPLOYER} and re-run:" >&2
	case "$TARGET" in
		sepolia) echo "  https://portal.cdp.coinbase.com/products/faucet  (Base Sepolia ETH)" >&2 ;;
		vibenet) echo "  https://faucet.vibes.base.org" >&2 ;;
	esac
	exit 1
fi

LOG_DIR="${ROOT}/.testnet"
mkdir -p "$LOG_DIR"
LOG="${LOG_DIR}/${TARGET}.log"

echo "==> deploying"
(cd packages/contracts && \
	PRIVATE_KEY="$DEPLOYER_PRIVATE_KEY" \
	VAULT_ASSET_ADDRESS="$ASSET" \
	forge script script/DeployTestnet.s.sol:DeployTestnet \
		--rpc-url "$RPC" --broadcast --slow \
		--gas-estimate-multiplier "$GAS_MULTIPLIER") | tee "$LOG" | tail -20

read_addr() { grep -m1 "^  $1" "$LOG" | awk '{print $NF}'; }

FACTORY="$(read_addr 'VaultFactory')"
FUND="$(read_addr 'InsuranceFund')"
USDC="$(read_addr 'Asset')"
START_BLOCK="$(read_addr 'StartBlock')"
CONSERVATIVE="$(read_addr 'Conservative')"
LEVERAGED="$(read_addr 'Leveraged')"

if [[ -z "$FACTORY" ]]; then
	echo "could not read the factory address out of ${LOG}" >&2
	exit 1
fi

cat > "$ENV_FILE" <<ENV
# Generated by scripts/testnet-up.sh ${TARGET} — overwritten on every run.
# Loaded on top of .env by \`scripts/dev.sh ${ENV_FILE}\`.

CHAIN_ID=${CHAIN_ID}
BASE_RPC_URL=${RPC}
PONDER_RPC_URL_BASE=${RPC}
VITE_BASE_RPC_URL=${RPC}

# Both of these are chains most wallets do not have. Describing them here is
# what lets the connect flow add them on demand.
VITE_CHAIN_ID=${CHAIN_ID}
VITE_CHAIN_RPC_URL=${RPC}
VITE_CHAIN_EXPLORER_URL=${EXPLORER}

USDC_ADDRESS=${USDC}
VAULT_FACTORY_ADDRESS=${FACTORY}
VITE_VAULT_FACTORY_ADDRESS=${FACTORY}
INSURANCE_FUND_ADDRESS=${FUND}
VAULT_FACTORY_START_BLOCK=${START_BLOCK}

VAULT_ADMIN_ADDRESS=${DEPLOYER}
VAULT_GUARDIAN_ADDRESS=${DEPLOYER}
INSURANCE_TREASURER_ADDRESS=${DEPLOYER}
ADMIN_ADDRESSES=${DEPLOYER}

# The perp leg runs against Pacifica's own testnet. It is a separate venue on a
# separate chain from the vault, so nothing about it is tied to which EVM
# testnet the vault sits on.
PACIFICA_API_URL=https://test-api.pacifica.fi/api/v1
SOLANA_RPC_URL=https://api.devnet.solana.com

TESTNET_VAULT_CONSERVATIVE=${CONSERVATIVE}
TESTNET_VAULT_LEVERAGED=${LEVERAGED}
TESTNET_EXPLORER=${EXPLORER}
ENV

echo
echo "==> ${TARGET} deployed"
echo "    Asset         ${USDC}"
echo "    InsuranceFund ${FUND}"
echo "    VaultFactory  ${FACTORY}   ${EXPLORER}/address/${FACTORY}"
echo "    Conservative  ${CONSERVATIVE}"
echo "    Leveraged     ${LEVERAGED}"
echo "    wrote ${ENV_FILE}"
echo
echo "    next: scripts/dev.sh ${ENV_FILE}"
